#
# gp-webrtc-firebase
# Copyright (c) 2024, Greg PFISTER. MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the “Software”), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

version: '3.9'

# Services
services:
  gp-webrtc-firebase:
    container_name: gp-webrtc-firebase
    user: vscode
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ..:/workspace
      - gp-webrtc-firebase-home:/home
    networks:
      - gp-webrtc-devenv-net
  # gp-webrtc-coturn:
  #   container_name: gp-webrtc-coturn
  #   image: coturn/coturn:4
  #   network_mode: 'host'
  #   expose:
  #     - '3478'
  #     # - '5349'
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '200k'
  #       max-file: '10'
  #   volumes:
  #     - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
  #     - gp-webrtc-firebase-coturn:/var/lib
  #     # - /etc/localtime:/etc/localtime:ro
  #     # - /etc/timezone:/etc/timezone:ro

volumes:
  gp-webrtc-firebase-home:
    name: gp-webrtc-firebase-home
  # gp-webrtc-firebase-coturn:
  #   name: gp-webrtc-firebase-coturn

networks:
  gp-webrtc-devenv-net:
    name: gp-webrtc-devenv-net
